### ISSUE TITLE
Baseline clinical factors

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#1]
Weight   loss 3 months prior to RT | kg
Reirradiation | LIST
_0 | No
-- | --
1 | Yes, first   reirradiation
2 | Yes, second   reirradiation_
Treatment for   local recurrence | YES/NO
Treatment for   regional recurrence | YES/NO

**Comment by riannefijten** [comment]
I could not find reirradiation in any ontology. Can we use "Irradiation", i.e.  [Radiation Therapy](https://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C15313&jump_to_nav=true), instead and somehow clarify that it's repeated irradiation?

**Comment by riannefijten** [comment]
Added all baseline clinical factors.
