### ISSUE TITLE
Proton therapy factors

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#11]
Number   of scenarios for robust evaluation | VALUE
Number of   beams | VALUE
Robust   treatment planning range uncertainty | %
Robustness   evaluation setup | mm
Layer   repainting (layers) | VALUE
Treatment type | LIST
_1 | SFO
2 | SMO_
Type of beam   absorber | LIST
_1 | Range shifter
2 | External absorber   standard
3 | Individual 3D print_
Dose   engine | LIST
_1 | Pencil beam
2 | Monte Carlo_
MC uncertainty | %

**Comment by matthijssloep** [comment]
no fitting ontology for: dose engine, treatment type, robustTreatmentPlanningRangeUncertainty and robustnessEvaluationSetup
