### ISSUE TITLE
Radiotherapy related factors: therapeutic target

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#14]
Date of   start therapeutic target RT | DATE
Last day of   therapeutic target RT | DATE
Fraction dose | VALUE
Number of   fractions | VALUE
Dose to OARs   treatment planning | LIST
_Code | Description | Left/right | Used for   optimization ? | Mean dose in Gy | Max dose in Gy
1 | Anterior segment of   the eyeball |   | YES/NO |   |  
2 | Posterior segment of   the eyeball |   | YES/NO |   |  
3 | Lacrimal gland |   | YES/NO |   |  
4 | Parotid glands |   | YES/NO |   |  
5 | Submandibular glands |   | YES/NO |   |  
6 | Extended oral cavity |   | YES/NO |   |  
7 | Buccal mucosa |   | YES/NO |   |  
8 | Lips |   | YES/NO |   |  
9 | Mandible |   | YES/NO |   |  
10 | Cochlea |   | YES/NO |   |  
  | Pharyngeal   constrictor muscles (PCM); |   | YES/NO |   |  
11 | PCM superior |   | YES/NO |   |  
12 | PCM medius |   | YES/NO |   |  
13 | PCM inferior |   | YES/NO |   |  
14 | Supraglottic larynx |   | YES/NO |   |  
15 | Glottic area |   | YES/NO |   |  
16 | Arytenoids |   | YES/NO |   |  
17 | Cricopharyngeal inlet |   | YES/NO |   |  
18 | Cervical oesophagus |   | YES/NO |   |  
19 | Brachial plexus |   | YES/NO |   |  
20 | Thyroid gland |   | YES/NO |   |  
21 | Brain |   | YES/NO |   |  
22 | Brainstem |   | YES/NO |   |  
23 | Pituitary gland |   | YES/NO |   |  
24 | Optic chiasm |   | YES/NO |   |  
25 | Optic nerve |   | YES/NO |   |  
26 | Spinal cord |   | YES/NO |   |  
27 | Carotid arteries |   | YES/NO |   |_

**Comment by matthijssloep** [comment]
no fitting ontology for: therapeuticTargetRT and doseToOARsTreatmentPlanning
