### ISSUE TITLE
Radiation-induced side effects

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#15]
Weight | kg
Xerostomia | CTCAEv4.0
Dysphagia | CTCAEv4.0
Dysphagia   (UMCG) | UMCG
Oral mucositis | CTCAEv4.0
Dermatitis   radiation | CTCAEv4.0
Osteoradionecrosis | CTCAEv4.0
Soft tissue   necrosis | CTCAEv4.0

**Comment by matthijssloep** [comment]
what to do with ctcae v4.0 grades and UMCG grades? Weight is weightloss?
