### ISSUE TITLE
Patient-reported outcome measures (PROM)

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#16]
EORTC   QLQ-H&N35 | questionnaire
EORTC QLQ-C30 | questionnaire
EUROQOL-5D | questionnaire

**Comment by matthijssloep** [comment]
- ampersand in EORTC QLQ-H&N35 is not accepted in the code
- what happens with the questionnaires? do they turn into a local value (list)
