### ISSUE TITLE
Tumor follow up

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#17]
Local   recurrence | YES/NO
If YES, date   of local recurrence | dd/mm/yyyy
Regional   recurrence | YES/NO
If YES, date   of regional recurrence | dd/mm/yyyy
Distant   metastases | YES/NO
If YES, date   of distant metastases | dd/mm/yyyy
New malignancy | YES/NO
If yes,   location of new malignancy | tekst
Date of last   follow up | dd/mm/yyyy
Status at last   follow up | LIST
_0 | Alive with no   evidence of disease
1 | Alive with failure   index tumour, successfully salvaged
2 | Alive with failure   index tumour not salvaged
3 | Dead from   intercurrent disease
4 | Dead from index   tumour_

**Comment by matthijssloep** [comment]
no fitting ontology for tumour follow up and for status at follow up
