### ISSUE TITLE
Diagnostics procedures and results

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#2]
Date MDO   decision treatment strategy | DATE
CT-scan head and neck | YES/NO
PET-CT | YES/NO
MRI-scan head   and neck | YES/NO
Ultrasound of   the neck | LIST
_0 | No
1 | Yes, no punction
2 | Yes, ultrasound neck   + FNAC negative
3 | Yes, ultrasound neck   + FNAC positive_
Sentinel node procedure | YES/NO

**Comment by riannefijten** [comment]
Unsure if location (neck) of scans/ultrasound can be assumed. I have implemented in with this assumption at the moment.
