### ISSUE TITLE
Systemic treatment

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#7]
Systemic   treatment | LIST
_0 | No systemic   treatment
1 | Primary concurrent   systemic treatment
2 | Induction systemic   treatment
3 | Postoperative   systemic treatment
4 | Induction +   concurrent systemic treatment_
Systemic   treatment: which drugs | LIST
_0 | Cisplatin   weekly
1 | Cisplatin 3-weekly
2 | Cetuximab
3 | 5FU and carboplatin
4 | TPF
5 | Other_
Systemic   treatment: number of cycles | VALUE
Systemic   treatment: start date | DATE
Systemic   treatment: stop date | DATE
Systemic   treatment: total dose administered | VALUE
Systemic   treatment: dose reduction? | YES/NO
Patient   included in clinical trial | YES/NO

**Comment by matthijssloep** [comment]
Systemic treatment: dose reduction? | YES/NO
For this line I've used the Dosed Reduced class from the NCIT ontology, not sure is this is the best fit. 

https://bioportal.bioontology.org/ontologies/NCIT/?p=classes&conceptid=http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C49505&jump_to_nav=true
