### ISSUE TITLE
Postoperative setting neck

### ISSUE THREAD

**Issue by andredekker** [maastroclinic/ProTRAIT-FAIRifier#9]
Surgery   of the neck | YES/NO
Date of   surgery of the neck | DATE
Pathological   N-stage (only in postop setting) | LIST
_Code | AJCC 7th   Edition | AJCC 8th   Edition
0 | N0 | N0
1 | N1 | N1
2 | N2a | N2a
3 | N2b | N2b
4 | N2c | N2c
5 | N3 | N3
6 | N2 | N2
9 | NX | NX_
Number of   lymph node metastases | VALUE
Number of   lymph node metastases checked at pathology | VALUE
Number of   lymph node metastases with ECS | VALUE

**Comment by matthijssloep** [comment]
no fitting ontology for numberOfLymphNodeMetastasesCheckedAtPathology and for numberOfLymphNodeMetastasesWithECS
